[envs.brili]
command = "bril2json < {filename} | brili -p {args}"
output.out = "-"
output.prof = "2"

[envs.in_ssa]
command = "bril2json < {filename} | python ../in_ssa_set_get.py | brili -p {args} "
output.out = "-"
output.ssa_prof = "2"